---
- name: Build Golden Image
  hosts: central

  tasks:
  - name: create mount  Directory
    file:
      path: "{{ISO_MOUNT_POINT}}"
      state: directory
      mode: 0777


  - name: mount ISO
    mount:
      path: "{{ISO_MOUNT_POINT}}"
      src: "{{ISO_PATH}}"
      opts: ro
      fstype: iso9660
      state: mounted

  - name: create New Directory
    file:
      path: "{{ISO_FILES_PATH}}"
      state: directory
      mode: 0775

  - name: Copy Contents to another location
    shell: " cp -rf {{ISO_MOUNT_POINT}}/* {{ISO_FILES_PATH}}/ "

  - name: copy kickstart file
    shell: "cp -rf  {{KS_FILE}} {{ISO_FILES_PATH}}/ks.cfg"

  - name: Copy isolinux.cfg
    shell: " cp -rf {{ISOLINUX_CFG}} {{ISO_FILES_PATH}}/isolinux/isolinux.cfg"

  - name: Rebuild ISO
    shell: "cd {{ISO_FILES_PATH}} ; mkisofs -o {{NEW_ISO_PATH}} -b isolinux/isolinux.bin -c isolinux/boot.cat --no-emul-boot --boot-load-size 4 --boot-info-table -J -R -V disks ."
  - name: unmount ISO
    shell: "umount {{ISO_MOUNT_POINT}}"
  - name: remove folders
    shell: "rm -rf {{ISO_MOUNT_POINT}} {{ISO_FILES_PATH}}"





