---
- name: Build Golden Image
  hosts: central

  tasks:
  - name: mount ISO
    mount:
      path: "{{ISO_MOUNT_POINT}}"
      src: "{{ISO_PATH}}"
      opts: ro
      state: present

  - name: create New Directory
    file:
      path: "{{ISO_FILES_PATH}}"
      state: directory
      mode: 0775

  - name: Copy Contents to another location
    copy: 
      src: "{{ISO_MOUNT_POINT}}" 
      dest: "{{ISO_FILES_PATH}}"  
      directory_mode: yes

  - name: copy kickstart file
    copy: 
      src: "{{KS_FILE}}"
      dest: "{{ISO_FILES_PATH}}/ks.cfg"

  - name: Copy isolinux.cfg
    copy: 
      src: "{{ISOLINUX_CFG}}" 
      dest: "{{ISO_FILES_PATH}}/isolinux/isolinux.cfg"

  - name: Rebuild ISO
    shell: "cd {{ISO_FILES_PATH}} ; mkisofs -o {{NEW_ISO_PATH}} -b isolinux/isolinux.bin -c isolinux/boot.cat --no-emul-boot --boot-load-size 4 --boot-info-table -J -R -V disks ."



